### ISSUE TITLE
Правким до ДЗ 21

### ISSUE THREAD

**Issue by Dexter19** [Irina77777777/Irina77777777.github.io#1]
10. Додати 'Catwoman' на початок масиву names, використовуючи оператор ...
Використатйте лператор спред( або його ще називають 3 крапки) для вирішення цієї задачі
Ось так: 
names = ['Batman', 'Joker', 'Bane'];
names = [
  'Catwoman',
  ...names
];

**Comment by Irina77777777** [comment]
Дякую, наче б все знайоме і синтаксис і спред, а сама не змогла , хоча стільки спробувала...
